service: my-lambda-service

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  role: ${env:MY_LAMBDA_ROLE_ARN}
  environment:
    OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  ingest:
    name: ingest-function
    handler: image_conversion_service/ingest.lambda_handler
    environment:
      OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}
      SOURCE_BUCKET: ${env:SOURCE_BUCKET}
      DESTINATION_BUCKET: ${env:DESTINATION_BUCKET}
      FAILED_INGESTION_BUCKET: ${env:FAILED_INGESTION_BUCKET}
  query:
    name: query-function
    handler: query_function/query.lambda_handler
    environment:
      OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}
      BEDROCK_ENDPOINT: ${env:BEDROCK_ENDPOINT}