service: lambda-services

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  role: ${env:LAMBDA_ROLE_ARN}
  environment:
    OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  ingest-from-ingestion:
    name: ingest-function-ingestion
    handler: image_conversion_service.ingest.lambda_handler
    events:
      - s3:
          bucket: ${env:INGESTION_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
    environment:
      OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}
      INGESTION_BUCKET: ${env:INGESTION_BUCKET}
      FAILED_INGESTION_BUCKET: ${env:FAILED_INGESTION_BUCKET}
      PROCESSED_INGESTION_BUCKET: ${env:PROCESSED_INGESTION_BUCKET}
  ingest-from-processed:
    name: ingest-function-processed
    handler: image_conversion_service.ingest.lambda_handler
    events:
      - s3:
          bucket: ${env:PROCESSED_INGESTION_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
    environment:
      OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}
      INGESTION_BUCKET: ${env:INGESTION_BUCKET}
      FAILED_INGESTION_BUCKET: ${env:FAILED_INGESTION_BUCKET}
      PROCESSED_INGESTION_BUCKET: ${env:PROCESSED_INGESTION_BUCKET}
  query:
    name: query-function
    handler: query_function.query.lambda_handler
    environment:
      OPENSEARCH_ENDPOINT: ${env:OPENSEARCH_ENDPOINT}
      BEDROCK_ENDPOINT: ${env:BEDROCK_ENDPOINT, 'default-endpoint'}