name: LambdaZip + Terraform Plan

on:
  push:
    branches:
      - '*'  # Trigger on any branch
  pull_request:
    branches:
      - '*'  # Trigger on any branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  zip-lambda-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies and zip ingest function
        run: |
          cd lambda_functions/ingest_function
          pip install -r requirements.txt -t .
          zip -r ../../ingest_function.zip .
          
      - name: Install dependencies and zip query function  
        run: |
          cd lambda_functions/query_function
          pip install -r requirements.txt -t .
          zip -r ../../query_function.zip .
        
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.1

      - name: Run Terraform Plan
        working-directory: ./terraform
        run: |
          terraform init
          terraform plan -var-file=terraform.tfvars -out=tfplan
    
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./terraform/
          if-no-files-found: error

  create-pr:
    needs: [zip-lambda-functions, terraform]
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR: Merge changes from ${{ github.ref_name }}"
          body: "This PR is automatically generated after a successful Terraform Plan run to merge changes into main."
          base: main
          branch: ${{ github.ref_name }}-auto-pr
          repository: ${{ github.repository }}