name: Terraform Apply & Serverless Deploy

on:
  push:
    branches:
      - main  # Only trigger on main branch
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.1
      
      # Initialize Terraform
      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init
      
      # ------------------------------
      # Phase 1: Infrastructure Deployment (without API Gateway integration)
      # ------------------------------
      - name: Terraform Apply (Phase 1 - Base Infrastructure)
        working-directory: ./terraform
        run: terraform apply -auto-approve -var "lambda_invoke_arn="
        # This will create the API Gateway but without Lambda integration
      
      # Export Terraform outputs for Serverless use
      - name: Export Terraform Outputs
        working-directory: ./terraform
        run: |
          echo "INGESTION_BUCKET=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
          echo "FAILED_INGESTION_BUCKET=$(terraform output -raw failed_ingestion_bucket)" >> $GITHUB_ENV
          echo "OPENSEARCH_ENDPOINT=$(terraform output -raw opensearch_domain_endpoint)" >> $GITHUB_ENV
          echo "LAMBDA_ROLE_ARN=$(terraform output -raw lambda_role_arn)" >> $GITHUB_ENV
      
      # ------------------------------
      # Phase 2: Serverless Lambda Deployment
      # ------------------------------
      # Set up Python for Lambda functions
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      # Set up Node.js for Serverless Framework
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      # Install Serverless Framework globally
      - name: Install Serverless Framework
        run: npm install -g serverless
        
      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # Install Serverless plugins if needed
      - name: Install Serverless plugins
        run: |
          if [ -f package.json ]; then npm ci; fi
          
      # Serverless Deploy
      - name: Serverless Deploy
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          LAMBDA_ROLE_ARN: ${{ env.LAMBDA_ROLE_ARN }}
          INGESTION_BUCKET: ${{ env.INGESTION_BUCKET }}
          FAILED_INGESTION_BUCKET: ${{ env.FAILED_INGESTION_BUCKET }}
          OPENSEARCH_ENDPOINT: ${{ env.OPENSEARCH_ENDPOINT }}
      
      # ------------------------------
      # Phase 3: Get Lambda ARN and Complete API Gateway Integration
      # ------------------------------
      - name: Get Lambda ARN for Ingest Function
        id: get_lambda_arn
        run: |
          LAMBDA_ARN=$(aws lambda get-function --function-name ingest-function --query 'Configuration.FunctionArn' --output text)
          echo "LAMBDA_INVOKE_ARN=$(echo $LAMBDA_ARN | sed 's/function/invocation/')" >> $GITHUB_ENV

      - name: Terraform Apply (Phase 3 - Complete API Gateway Integration)
        working-directory: ./terraform
        run: terraform apply -auto-approve -var "lambda_invoke_arn=${{ env.LAMBDA_INVOKE_ARN }}"