name: Terraform Apply

on:
  push:
    branches:
      - main  # Only trigger on main branch
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: read
  id-token: write  # Needed for AWS credential provider

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.1
          
      - name: Find latest workflow run with artifact
        id: find-artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Install GitHub CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
          
          # Find the latest successful run of the terraform plan workflow with an artifact
          ARTIFACT_URL=$(gh api repos/${{ github.repository }}/actions/artifacts \
            --jq '.artifacts[] | select(.name=="tfplan" and .expired==false) | .archive_download_url' \
            --header "Accept: application/vnd.github+json" \
            | head -n 1)
          
          if [ -z "$ARTIFACT_URL" ]; then
            echo "No tfplan artifact found. Unable to proceed with terraform apply."
            exit 1
          else
            echo "Found artifact URL: $ARTIFACT_URL"
            echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_OUTPUT
          fi

      - name: Download Terraform Plan Artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p terraform
          curl -L -H "Authorization: token ${{ github.token }}" \
               -H "Accept: application/vnd.github+json" \
               "${{ steps.find-artifact.outputs.artifact_url }}" \
               -o terraform/tfplan.zip
          cd terraform && unzip tfplan.zip && rm tfplan.zip

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve tfplan